apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: gremlin
spec:
  collectors:
    - logs:
        selector:
          - app.kubernetes.io/name=chao
        namespace: gremlin
    - logs:
        selector:
          - app.kubernetes.io/name=gremlin
        namespace: gremlin
    - helm:
        namespace: "gremlin"
